task: sst2
model: "roberta-base"
seed: 43
epochs: 3
device: "cuda:0"
log_file: "results.csv"
use_wandb: true
wandb_entity: "gusevski"
wandb_project: "Multi-vs-single-task-classifiers"

TRAINING_ARGS:
  per_device_train_batch_size: 32
  per_device_eval_batch_size: 64
  learning_rate: 5e-5
  weight_decay: 0.01
  lr_scheduler_type: "linear"
  evaluation_strategy: "epoch"
  save_strategy: "epoch"
  save_total_limit: 3
  logging_steps: 20
  output_dir: "./outputs/" #"./results/"
  load_best_model_at_end: True